exec costing '2017-05',10
delete from COST_DAY_CALCULATE
delete from COST_MONTH_CALCULATE
delete from COST_DEPT_CALCULATE
delete from COST_DEPT_MONTH_CALCULATE

select * from COST_DAY_CALCULATE
select * from COST_MONTH_CALCULATE
select * from COST_DEPT_CALCULATE
select * from COST_DEPT_MONTH_CALCULATE

select top 1 * from COST_DIRECT_LABOUR_ATTENDANCE

select SALE_TYPE_NAME 营业类型,dept_name 部门,CMONTH 日期,DIRECT_HOURS 直接人工小时数,DIRECT_COST 直接人工成本,INDIRECT_HOURS 间接人工小时数,INDIRECT_COST 间接人工成本,POINTCOUNT 点数,COST 预估成本,COST_POINT 预估单点成本,STANDARD_POINT 标准单点成本,STANDARD_COST 标准成本,PROFIT 盈亏 from COST_DEPT_CALCULATE